######## joseki node recalculation

cmd=josekinoderecalculate
debug=false

# baseurl=http://localhost:8081/
baseurl=https://staging.josekipedia.com/
katago=/opt/homebrew/bin/katago
kata.config=/opt/homebrew/Cellar/katago/1.16.3/share/katago/configs/analysis_example.cfg
kata.model=/Users/baibonjwa/goproblems/katago/kata1-b15c192-s1672170752-d466197061.txt.gz
kata.human_model=/Users/baibonjwa/goproblems/katago/b18c384nbt-humanv0.bin.gz

apikey=unused
api.joseki.nodes=api/joseki-nodes
api.joseki.analysis_results=api/joseki-analysis-results

######## katago settings
kata.debug_print=false
kata.print_analyzer_query=false
kata.print_summary_result=false
kata.query.timeout.ms=60000

######## joseki analysis settings
joseki.visits=1000
joseki.komi=6.5
joseki.max_move_distance=4
# joseki.analysis_scopes=local
joseki.analysis_scopes=local,local_with_moves,global
# joseki.human_sl_rank=3d

# joseki.api_max_attempts=20
# joseki.api_retry_delay_ms=5000

# Optional filters for focused recalculation.
sort=breadth
# path=
# pathPrefix=Q16,R17
# includeDeleted=true
