package autoprob.api;

public enum EndnessReasonCode {
    LOW_URGENCY,
    SIGNIFICANT_SCORE_CHANGE,
    COMPUTER_WANTS_TENUKI,
    MAX_DEPTH_REACHED,
    NO_SENTE,
    NO_VALID_COMPUTER_RESPONSE_INSIDE_AREA,
    NO_VALID_COMPUTER_RESPONSE,
    NO_VALID_MAX_RESPONSE,
    MIN_MOVES_NOT_REACHED,
    SUCCESS_NOT_ALLOWED_ON_COMPUTER_MOVE,
    FAILURE_NOT_ALLOWED_ON_PLAYER_MOVE,
    OWNERSHIP_UNCLEAR,
    STRONG_PLAYER_MOVE,
    NO_VALUABLE_PLAYER_MOVE_AFTER_SUCCESS,
    OWNERSHIP_SAMPLE_TOO_SMALL
}
